### ISSUE TITLE
Manipulating server codes.

### ISSUE THREAD

**Issue by KapsonLabs** [kalsmic/iReporterApi#22]
I honestly don't know what the the LFA's think about manipulating server codes in the API response message. But status `200` from the server means that the server properly handled the request with no error and successfully returned a `404` message if the resource doesn't exist. A 500 means internal server error therefore the sever or application failed somewhere and the dev can check the logs via `syslog` to find out what exactly happened. 

So a response that follows the the format of `{'status' 404, 'error': 'Resource doesn't exist'}, 404`

 the trailing `404` outside the jsonify method manipulates the server code from `200` to `404`.

I need more clarification on this matter @codephillip @EdisonAbah @KengoWada

**Comment by KapsonLabs** [comment]
Example code from the repo is below.
`return (
            jsonify({"error": "Bad authorization header", "status": 400}),
            400,
        )`
 
The trailing `400` changes the server response from `200` to `400`........ Need clarification on this. @kalsmic @KengoWada @codephillip

**Comment by kalsmic** [comment]
@KapsonLabs , What you're saying is right and it's actually good to explicitly declare that trailing status code because then for the server would only return a 404 error only in scenarios where the resource ("endpoint") doesn't exist but you realize that in the API we want to still return a 404 error when the resource ("item in collection") does not exist.

**Comment by kalsmic** [comment]
I was nice having this discussion, I really wanted it to continue but I guess it did not get much attention from our other colleagues. It is a very interesting one.
